# Generated by Django 5.0 on 2024-01-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login_page', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number_of_faces', models.IntegerField(default=0)),
                ('number_of_men', models.IntegerField(default=0)),
                ('number_of_women', models.IntegerField(default=0)),
                ('male_emotions', models.JSONField(default=dict)),
                ('female_emotions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
                ('field2', models.IntegerField()),
            ],
        ),
    ]
