# Generated by Django 5.0 on 2024-01-09 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login_page', '0004_facedata_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData2',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number_of_faces', models.IntegerField(default=0)),
                ('number_of_men', models.IntegerField(default=0)),
                ('number_of_women', models.IntegerField(default=0)),
                ('male_emotions', models.JSONField(default=dict)),
                ('female_emotions', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='facedata',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
