# Generated by Django 5.0 on 2024-01-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_facedata2_facedata_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata2',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='gender_tag',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='number_of_men',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='number_of_women',
            field=models.IntegerField(default=0),
        ),
    ]
