# Generated by Django 5.0 on 2024-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0006_facedata2_total_time_video_gender_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gender_tag',
            field=models.CharField(max_length=10),
        ),
    ]
