# Generated by Django 5.0 on 2024-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0007_alter_video_gender_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='number_of_men',
        ),
        migrations.RemoveField(
            model_name='video',
            name='number_of_women',
        ),
        migrations.AddField(
            model_name='video',
            name='gender_comp',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
