# Generated by Django 5.0 on 2024-01-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0008_remove_video_number_of_men_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='gender_comp',
        ),
    ]
