# Generated by Django 5.0 on 2024-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0009_remove_video_gender_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata2',
            name='is_reset_this_month',
            field=models.BooleanField(default=False),
        ),
    ]
